<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_Stop" Id="{3e354bcb-4e4f-4b34-9851-51b9542d0760}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Stop
VAR_INPUT
(*È«¾Ö*)
	Mode:DINT;
	PowerState:BOOL;
	CoupleState:DINT;
	(*GapMode*)
	GapStop:BOOL;
	(*BCGapMode*)
	BCGapStop:BOOL;
	(*SingleCarrierMode*)
	TopStop:BOOL;
	BottomStop:BOOL;
	InStop:BOOL;
	OutStop:BOOL;
	(*DebugMode*)
	LeftTopStop:BOOL;
	RightTopStop:BOOL;
	LeftBottomStop:BOOL;
	RightBottomStop:BOOL;
	LeftInStop:BOOL;
	RightInStop:BOOL;
	LeftOutStop:BOOL;
	RightOutStop:BOOL;
END_VAR
VAR_OUTPUT
	FbID:DINT:=1001;
	GapState:DINT;
	GapBusy:BOOL;
	GapDone:BOOL;

	BCGapState:DINT;
	BCGapBusy:BOOL;
	BCGapDone:BOOL;

	TopState:DINT;
	TopBusy:BOOL;
	TopDone:BOOL;
	BottomState:DINT;
	BottomBusy:BOOL;
	BottomDone:BOOL;
	InState:DINT;
	InBusy:BOOL;
	InDone:BOOL;
	OutState:DINT;
	OutBusy:BOOL;
	OutDone:BOOL;

	LeftTopState:DINT;
	LeftTopBusy:BOOL;
	LeftTopDone:BOOL;
	RightTopState:DINT;
	RightTopBusy:BOOL;
	RightTopDone:BOOL;
	LeftBottomState:DINT;
	LeftBottomBusy:BOOL;
	LeftBottomDone:BOOL;
	RightBottomState:DINT;
	RightBottomBusy:BOOL;
	RightBottomDone:BOOL;
	LeftInState:DINT;
	LeftInBusy:BOOL;
	LeftInDone:BOOL;
	RightInState:DINT;
	RightInBusy:BOOL;
	RightInDone:BOOL;
	LeftOutState:DINT;
	LeftOutBusy:BOOL;
	LeftOutDone:BOOL;
	RightOutState:DINT;
	RightOutBusy:BOOL;
	RightOutDone:BOOL;

	Error:BOOL;
	ErrorID:DINT;
END_VAR
VAR
	LeftTop_MC_Stop: MC_Stop;
	LeftBottom_MC_Stop: MC_Stop;
	RightTopLin_MC_Stop: MC_Stop;
	RightBottomLin_MC_Stop: MC_Stop;
	LeftIn_MC_Stop: MC_Stop;
	LeftOut_MC_Stop: MC_Stop;
	RightInLin_MC_Stop: MC_Stop;
	RightOutLin_MC_Stop: MC_Stop;
	fb_ton: TON;
	fb_ton1: TON;
	fb_ton2: TON;
	fb_ton3: TON;
	fb_ton4: TON;
	fb_ton_debug_1:TON;
	fb_ton_debug_2:TON;
	fb_ton_debug_3:TON;
	fb_ton_debug_4:TON;
	fb_ton_debug_5:TON;
	fb_ton_debug_6:TON;
	fb_ton_debug_7:TON;
	fb_ton_debug_8:TON;
	fb_ton_BC: TON;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF PowerState=1 THEN
	IF Mode=1 AND TopStop THEN
		A_TopStop();
	ELSIF Mode=1 AND BottomStop THEN
		A_BottomStop();
	ELSIF Mode=2 AND LeftTopStop THEN
		A_LeftTopStop();
	ELSIF Mode=2 AND RightTopStop THEN
		A_RightTopStop();
	ELSIF Mode=2 AND LeftBottomStop THEN
		A_LeftBottomStop();
	ELSIF Mode=2 AND RightBottomStop THEN
		A_RightBottomStop();
	ELSIF Mode=3 AND BCGapStop THEN
		A_BCGapStop();
	ELSE
		FB_PlcEmergencyStop();
	END_IF
END_IF
]]></ST>
    </Implementation>
    <Folder Name="Debug" Id="{104af77a-ff55-4e7d-ae89-0786c90d6988}" />
    <Folder Name="SingleCarrier" Id="{5f2d3879-30be-4d08-a393-873fa14fb1eb}" />
    <Folder Name="UserMode" Id="{c0a55f07-0d1e-4846-a7f6-2b5ce6b13305}" />
    <Action Name="A_BCGapStop" Id="{09d39807-0cc9-4816-a94c-73c13504c1f7}" FolderPath="UserMode\">
      <Implementation>
        <ST><![CDATA[IF BCGapStop THEN
BCGapBusy:=TRUE;
BCGapDone:=FALSE;
fb_ton_BC(PT:=t#100ms);
A_StopMC();
CASE BCGapState OF
	0:
		IF LeftTop_MC_Stop.Error OR LeftBottom_MC_Stop.Error 
			OR RightTopLin_MC_Stop.Error OR RightBottomLin_MC_Stop.Error
			OR  LeftIn_MC_Stop.Error OR LeftOut_MC_Stop.Error 
			OR RightInLin_MC_Stop.Error OR RightOutLin_MC_Stop.Error THEN
			ErrorID:=1;
			BCGapState:=-100;
			LeftTop_MC_Stop.Execute:=FALSE;
			LeftBottom_MC_Stop.Execute:=FALSE;
			RightTopLin_MC_Stop.Execute:=FALSE;
			RightBottomLin_MC_Stop.Execute:=FALSE;
			LeftIn_MC_Stop.Execute:=FALSE;
			LeftOut_MC_Stop.Execute:=FALSE;
			RightInLin_MC_Stop.Execute:=FALSE;
			RightOutLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			BCGapState:=1;
		END_IF
	1:
		LeftTop_MC_Stop.Execute:=TRUE;
		LeftBottom_MC_Stop.Execute:=TRUE;
		RightTopLin_MC_Stop.Execute:=TRUE;
		RightBottomLin_MC_Stop.Execute:=TRUE;
		LeftIn_MC_Stop.Execute:=TRUE;
		LeftOut_MC_Stop.Execute:=TRUE;
		RightInLin_MC_Stop.Execute:=TRUE;
		RightOutLin_MC_Stop.Execute:=TRUE;
		fb_ton_BC.IN:=TRUE;
		BCGapState:=2;
	2:
		IF  NOT LeftTop_MC_Stop.Done OR NOT LeftBottom_MC_Stop.Done 
			OR NOT RightTopLin_MC_Stop.Done OR NOT RightBottomLin_MC_Stop.Done
  			OR NOT LeftIn_MC_Stop.Done OR NOT LeftOut_MC_Stop.Done 
			OR NOT RightInLin_MC_Stop.Done OR NOT RightOutLin_MC_Stop.Done THEN
				BCGapState:=2;
		ELSE
			BCGapState:=88;
			LeftTop_MC_Stop.Execute:=FALSE;
			LeftBottom_MC_Stop.Execute:=FALSE;
			RightTopLin_MC_Stop.Execute:=FALSE;
			RightBottomLin_MC_Stop.Execute:=FALSE;			
			LeftIn_MC_Stop.Execute:=FALSE;
			LeftOut_MC_Stop.Execute:=FALSE;
			RightInLin_MC_Stop.Execute:=FALSE;
			RightOutLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		BCGapStop:=FALSE;
		BCGapState:=0;
		BCGapBusy:=FALSE;
		BCGapDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_BC.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		BCGapStop:=FALSE;
		BCGapState:=-100;
		BCGapBusy:=FALSE;
		BCGapDone:=FALSE;
		Error:=TRUE;
		LeftTop_MC_Stop.Execute:=FALSE;
		LeftBottom_MC_Stop.Execute:=FALSE;
		RightTopLin_MC_Stop.Execute:=FALSE;
		RightBottomLin_MC_Stop.Execute:=FALSE;			
		LeftIn_MC_Stop.Execute:=FALSE;
		LeftOut_MC_Stop.Execute:=FALSE;
		RightInLin_MC_Stop.Execute:=FALSE;
		RightOutLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_BC.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_BottomStop" Id="{3e5d2212-d55d-4178-a1aa-10c2e89eefb4}" FolderPath="SingleCarrier\">
      <Implementation>
        <ST><![CDATA[IF BottomStop THEN
BottomBusy:=TRUE;
BottomDone:=FALSE;
fb_ton2(PT:=t#100ms);
A_StopMC();
CASE BottomState OF
	0:
		IF LeftBottom_MC_Stop.Error OR RightBottomLin_MC_Stop.Error THEN
			ErrorID:=1;
			BottomState:=-100;
			LeftBottom_MC_Stop.Execute:=FALSE;
			RightBottomLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			BottomState:=1;
		END_IF
	1:
		LeftBottom_MC_Stop.Execute:=TRUE;
		RightBottomLin_MC_Stop.Execute:=TRUE;
		fb_ton2.IN:=TRUE;
		BottomState:=2;
	2:
		IF  NOT LeftBottom_MC_Stop.Done OR NOT LeftBottom_MC_Stop.Done THEN
				BottomState:=2;
		ELSE
			BottomState:=88;
			LeftBottom_MC_Stop.Execute:=FALSE;
			RightBottomLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		BottomStop:=FALSE;
		BottomState:=0;
		BottomBusy:=FALSE;
		BottomDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton2.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		BottomStop:=FALSE;
		BottomState:=-100;
		BottomBusy:=FALSE;
		BottomDone:=FALSE;
		Error:=TRUE;
		LeftBottom_MC_Stop.Execute:=FALSE;
		RightBottomLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton2.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_InStop" Id="{f06e74fd-318c-415b-ac2b-adabc6072b86}" FolderPath="SingleCarrier\">
      <Implementation>
        <ST><![CDATA[IF InStop THEN
InBusy:=TRUE;
InDone:=FALSE;
fb_ton3(PT:=t#100ms);
A_StopMC();
CASE InState OF
	0:
		IF LeftIn_MC_Stop.Error OR RightInLin_MC_Stop.Error THEN
			ErrorID:=1;
			InState:=-100;
			LeftIn_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			InState:=1;
		END_IF
	1:
		LeftIn_MC_Stop.Execute:=TRUE;
		RightInLin_MC_Stop.Execute:=TRUE;
		fb_ton3.IN:=TRUE;
		InState:=2;
	2:
		IF  NOT LeftIn_MC_Stop.Done OR NOT RightInLin_MC_Stop.Done THEN
				InState:=2;
		ELSE
			InState:=88;
			LeftIn_MC_Stop.Execute:=FALSE;
			RightInLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		InStop:=FALSE;
		InState:=0;
		InBusy:=FALSE;
		InDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton3.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		InStop:=FALSE;
		InState:=-100;
		InBusy:=FALSE;
		InDone:=FALSE;
		Error:=TRUE;
		LeftIn_MC_Stop.Execute:=FALSE;
		RightInLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton3.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_LeftBottomStop" Id="{cab19fe7-18d8-423d-84e7-b2a63e643950}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF LeftBottomStop THEN
LeftBottomBusy:=TRUE;
LeftBottomDone:=FALSE;
fb_ton_debug_3(PT:=t#100ms);
A_StopMC();
CASE LeftBottomState OF
	0:
		IF LeftBottom_MC_Stop.Error THEN
			ErrorID:=41;
			LeftBottomState:=-100;
			LeftBottom_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			LeftBottomState:=1;
		END_IF
	1:
		LeftBottom_MC_Stop.Execute:=TRUE;
		fb_ton_debug_3.IN:=TRUE;
		LeftBottomState:=2;
	2:
		IF  NOT LeftBottom_MC_Stop.Done THEN
				LeftBottomState:=2;
		ELSE
			LeftBottomState:=88;
			LeftBottom_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		LeftBottomStop:=FALSE;
		LeftBottomState:=0;
		LeftBottomBusy:=FALSE;
		LeftBottomDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_3.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		LeftBottomStop:=FALSE;
		LeftBottomState:=-100;
		LeftBottomBusy:=FALSE;
		LeftBottomDone:=FALSE;
		Error:=TRUE;
		LeftBottom_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_3.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_LeftInStop" Id="{f91b09e3-f669-4f08-abb4-4e66bddd882d}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF LeftInStop THEN
LeftInBusy:=TRUE;
LeftInDone:=FALSE;
fb_ton_debug_4(PT:=t#100ms);
A_StopMC();
CASE LeftInState OF
	0:
		IF LeftIn_MC_Stop.Error THEN
			ErrorID:=41;
			LeftInState:=-100;
			LeftIn_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			LeftInState:=1;
		END_IF
	1:
		LeftIn_MC_Stop.Execute:=TRUE;
		fb_ton_debug_4.IN:=TRUE;
		LeftInState:=2;
	2:
		IF  NOT LeftIn_MC_Stop.Done THEN
				LeftInState:=2;
		ELSE
			LeftInState:=88;
			LeftIn_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		LeftInStop:=FALSE;
		LeftInState:=0;
		LeftInBusy:=FALSE;
		LeftInDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_4.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		LeftInStop:=FALSE;
		LeftInState:=-100;
		LeftInBusy:=FALSE;
		LeftInDone:=FALSE;
		Error:=TRUE;
		LeftIn_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_4.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_LeftOutStop" Id="{c9624617-5b4c-46c3-afa1-8314afa61125}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF LeftOutStop THEN
LeftOutBusy:=TRUE;
LeftOutDone:=FALSE;
fb_ton_debug_7(PT:=t#100ms);
A_StopMC();
CASE LeftOutState OF
	0:
		IF LeftOut_MC_Stop.Error THEN
			ErrorID:=41;
			LeftOutState:=-100;
			LeftOut_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			LeftOutState:=1;
		END_IF
	1:
		LeftOut_MC_Stop.Execute:=TRUE;
		fb_ton_debug_7.IN:=TRUE;
		LeftOutState:=2;
	2:
		IF  NOT LeftOut_MC_Stop.Done THEN
				LeftOutState:=2;
		ELSE
			LeftOutState:=88;
			LeftOut_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		LeftOutStop:=FALSE;
		LeftOutState:=0;
		LeftOutBusy:=FALSE;
		LeftOutDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_7.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		LeftOutStop:=FALSE;
		LeftOutState:=-100;
		LeftOutBusy:=FALSE;
		LeftOutDone:=FALSE;
		Error:=TRUE;
		LeftOut_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_7.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_LeftTopStop" Id="{2b524d72-b139-4ac0-8fb1-7a7578319dea}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF LeftTopStop THEN
LeftTopBusy:=TRUE;
LeftTopDone:=FALSE;
fb_ton_debug_1(PT:=t#100ms);
A_StopMC();
CASE LeftTopState OF
	0:
		IF LeftTop_MC_Stop.Error THEN
			ErrorID:=41;
			LeftTopState:=-100;
			LeftTop_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			LeftTopState:=1;
		END_IF
	1:
		LeftTop_MC_Stop.Execute:=TRUE;
		fb_ton_debug_1.IN:=TRUE;
		LeftTopState:=2;
	2:
		IF  NOT LeftTop_MC_Stop.Done THEN
				LeftTopState:=2;
		ELSE
			LeftTopState:=88;
			LeftTop_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		LeftTopStop:=FALSE;
		LeftTopState:=0;
		LeftTopBusy:=FALSE;
		LeftTopDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_1.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		LeftTopStop:=FALSE;
		LeftTopState:=-100;
		LeftTopBusy:=FALSE;
		LeftTopDone:=FALSE;
		Error:=TRUE;
		LeftTop_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_1.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_OutStop" Id="{7cd401e6-bd12-4ae4-a499-be9296d9c5d9}" FolderPath="SingleCarrier\">
      <Implementation>
        <ST><![CDATA[IF OutStop THEN
OutBusy:=TRUE;
OutDone:=FALSE;
fb_ton4(PT:=T#100MS);
A_StopMC();
CASE OutState OF
	0:
		IF LeftOut_MC_Stop.Error OR RightOutLin_MC_Stop.Error THEN
			ErrorID:=1;
			OutState:=-100;
			LeftOut_MC_Stop.Execute:=FALSE;
			RightOutLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			OutState:=1;
		END_IF
	1:
		LeftOut_MC_Stop.Execute:=TRUE;
		RightOutLin_MC_Stop.Execute:=TRUE;
		fb_ton4.IN:=TRUE;
		OutState:=2;
	2:
		IF  NOT LeftOut_MC_Stop.Done OR NOT LeftOut_MC_Stop.Done THEN
				OutState:=2;
		ELSE
			OutState:=88;
			LeftOut_MC_Stop.Execute:=FALSE;
			RightOutLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		OutStop:=FALSE;
		OutState:=0;
		OutBusy:=FALSE;
		OutDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton4.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		OutStop:=FALSE;
		OutState:=-100;
		OutBusy:=FALSE;
		OutDone:=FALSE;
		Error:=TRUE;
		LeftOut_MC_Stop.Execute:=FALSE;
		RightOutLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton4.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_RightBottomStop" Id="{e95ff139-ca76-4481-866d-edf0363d8b42}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF RightBottomStop THEN
RightBottomBusy:=TRUE;
RightBottomDone:=FALSE;
fb_ton_debug_4(PT:=t#100ms);
A_StopMC();
CASE RightBottomState OF
	0:
		IF RightBottomLin_MC_Stop.Error THEN
			ErrorID:=41;
			RightBottomState:=-100;
			RightBottomLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			RightBottomState:=1;
		END_IF
	1:
		RightBottomLin_MC_Stop.Execute:=TRUE;
		fb_ton_debug_4.IN:=TRUE;
		RightBottomState:=2;
	2:
		IF  NOT RightBottomLin_MC_Stop.Done THEN
				RightBottomState:=2;
		ELSE
			RightBottomState:=88;
			RightBottomLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		RightBottomStop:=FALSE;
		RightBottomState:=0;
		RightBottomBusy:=FALSE;
		RightBottomDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_4.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		RightBottomStop:=FALSE;
		RightBottomState:=-100;
		RightBottomBusy:=FALSE;
		RightBottomDone:=FALSE;
		Error:=TRUE;
		RightBottomLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_4.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_RightInStop" Id="{2cda54c4-d20f-4c2e-a0eb-d55ad846c492}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF RightInStop THEN
RightInBusy:=TRUE;
RightInDone:=FALSE;
fb_ton_debug_6(PT:=t#100ms);
A_StopMC();
CASE RightInState OF
	0:
		IF RightInLin_MC_Stop.Error THEN
			ErrorID:=41;
			RightInState:=-100;
			RightInLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			RightInState:=1;
		END_IF
	1:
		RightInLin_MC_Stop.Execute:=TRUE;
		fb_ton_debug_6.IN:=TRUE;
		RightInState:=2;
	2:
		IF  NOT RightInLin_MC_Stop.Done THEN
				RightInState:=2;
		ELSE
			RightInState:=88;
			RightInLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		RightInStop:=FALSE;
		RightInState:=0;
		RightInBusy:=FALSE;
		RightInDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_6.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		RightInStop:=FALSE;
		RightInState:=-100;
		RightInBusy:=FALSE;
		RightInDone:=FALSE;
		Error:=TRUE;
		RightInLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_6.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_RightOutStop" Id="{81ad3fea-d849-44a0-8cfd-690db5e1ec0a}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF RightOutStop THEN
RightOutBusy:=TRUE;
RightOutDone:=FALSE;
fb_ton_debug_8(PT:=t#100ms);
A_StopMC();
CASE RightOutState OF
	0:
		IF RightOutLin_MC_Stop.Error THEN
			ErrorID:=41;
			RightOutState:=-100;
			RightOutLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			RightOutState:=1;
		END_IF
	1:
		RightOutLin_MC_Stop.Execute:=TRUE;
		fb_ton_debug_8.IN:=TRUE;
		RightOutState:=2;
	2:
		IF  NOT RightOutLin_MC_Stop.Done THEN
				RightOutState:=2;
		ELSE
			RightOutState:=88;
			RightOutLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		RightOutStop:=FALSE;
		RightOutState:=0;
		RightOutBusy:=FALSE;
		RightOutDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_8.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		RightOutStop:=FALSE;
		RightOutState:=-100;
		RightOutBusy:=FALSE;
		RightOutDone:=FALSE;
		Error:=TRUE;
		RightOutLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_8.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_RightTopStop" Id="{81452b6a-45dc-414d-8661-6860831ad67d}" FolderPath="Debug\">
      <Implementation>
        <ST><![CDATA[IF RightTopStop THEN
RightTopBusy:=TRUE;
RightTopDone:=FALSE;
fb_ton_debug_2(PT:=t#100ms);
A_StopMC();
CASE RightTopState OF
	0:
		IF RightTopLin_MC_Stop.Error THEN
			ErrorID:=41;
			RightTopState:=-100;
			RightTopLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			RightTopState:=1;
		END_IF
	1:
		RightTopLin_MC_Stop.Execute:=TRUE;
		fb_ton_debug_2.IN:=TRUE;
		RightTopState:=2;
	2:
		IF  NOT RightTopLin_MC_Stop.Done THEN
				RightTopState:=2;
		ELSE
			RightTopState:=88;
			RightTopLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		RightTopStop:=FALSE;
		RightTopState:=0;
		RightTopBusy:=FALSE;
		RightTopDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton_debug_2.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		RightTopStop:=FALSE;
		RightTopState:=-100;
		RightTopBusy:=FALSE;
		RightTopDone:=FALSE;
		Error:=TRUE;
		RightTopLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton_debug_2.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_StopMC" Id="{b171a3f0-94b4-4ac2-92c0-8ca964cc4005}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"LeftTop_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">2L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">4L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">5L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">6L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">7L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">8L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">10L</v>
                            </o>
                            <v n="Id">9L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">12L</v>
                            </o>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">14L</v>
                            </o>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">16L</v>
                            </o>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"LeftTopLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">18L</v>
                            </o>
                            <v n="Id">17L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">3L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"LeftBottom_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">20L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">22L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">23L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">24L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">25L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">26L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">28L</v>
                            </o>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">30L</v>
                            </o>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">32L</v>
                            </o>
                            <v n="Id">31L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">34L</v>
                            </o>
                            <v n="Id">33L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"LeftBottomLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">36L</v>
                            </o>
                            <v n="Id">35L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">21L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">19L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"RightTopLin_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">38L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">40L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">41L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">42L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">43L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">44L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">46L</v>
                            </o>
                            <v n="Id">45L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">48L</v>
                            </o>
                            <v n="Id">47L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">50L</v>
                            </o>
                            <v n="Id">49L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">52L</v>
                            </o>
                            <v n="Id">51L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"RightTopLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">54L</v>
                            </o>
                            <v n="Id">53L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">39L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">37L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"RightBottomLin_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">56L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">58L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">59L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">60L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">61L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">62L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">64L</v>
                            </o>
                            <v n="Id">63L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">66L</v>
                            </o>
                            <v n="Id">65L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">68L</v>
                            </o>
                            <v n="Id">67L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">70L</v>
                            </o>
                            <v n="Id">69L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"RightBottomLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">72L</v>
                            </o>
                            <v n="Id">71L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">57L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">55L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"LeftIn_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">77L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">79L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">80L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">81L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">82L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">83L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">85L</v>
                            </o>
                            <v n="Id">84L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">87L</v>
                            </o>
                            <v n="Id">86L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">89L</v>
                            </o>
                            <v n="Id">88L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">91L</v>
                            </o>
                            <v n="Id">90L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"LeftInLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">93L</v>
                            </o>
                            <v n="Id">92L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">78L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">73L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"LeftOut_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">94L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">96L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">97L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">98L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">99L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">100L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">102L</v>
                            </o>
                            <v n="Id">101L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">104L</v>
                            </o>
                            <v n="Id">103L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">106L</v>
                            </o>
                            <v n="Id">105L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">108L</v>
                            </o>
                            <v n="Id">107L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"LeftOutLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">110L</v>
                            </o>
                            <v n="Id">109L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">95L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">74L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"RightInLin_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">111L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">113L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">114L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">115L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">116L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">117L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">119L</v>
                            </o>
                            <v n="Id">118L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">121L</v>
                            </o>
                            <v n="Id">120L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">123L</v>
                            </o>
                            <v n="Id">122L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">125L</v>
                            </o>
                            <v n="Id">124L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"RightInLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">127L</v>
                            </o>
                            <v n="Id">126L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">112L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">75L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_Stop"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"RightOutLin_MC_Stop"</v>
                          <v n="Type">"MC_Stop"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">128L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">130L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">131L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">132L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">133L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">134L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">136L</v>
                            </o>
                            <v n="Id">135L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">138L</v>
                            </o>
                            <v n="Id">137L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">140L</v>
                            </o>
                            <v n="Id">139L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">142L</v>
                            </o>
                            <v n="Id">141L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"RightOutLin"</v>
                              <v n="Type">"axis_ref"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">144L</v>
                            </o>
                            <v n="Id">143L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Deceleration</v>
                            <v>Jerk</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>LREAL</v>
                            <v>ST_MoveOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Active</v>
                            <v>CommandAborted</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">129L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">76L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="A_TopStop" Id="{35574051-d064-41d9-8c90-d1d9b62d4922}" FolderPath="SingleCarrier\">
      <Implementation>
        <ST><![CDATA[IF TopStop THEN
TopBusy:=TRUE;
TopDone:=FALSE;
fb_ton1(PT:=t#100ms);
A_StopMC();
CASE TopState OF
	0:
		IF LeftTop_MC_Stop.Error OR RightTopLin_MC_Stop.Error THEN
			ErrorID:=1;
			TopState:=-100;
			LeftTop_MC_Stop.Execute:=FALSE;
			A_StopMC();
		ELSE
			TopState:=1;
		END_IF
	1:
		LeftTop_MC_Stop.Execute:=TRUE;
		RightTopLin_MC_Stop.Execute:=TRUE;
		fb_ton1.IN:=TRUE;
		TopState:=2;
	2:
		IF  NOT LeftTop_MC_Stop.Done OR NOT RightTopLin_MC_Stop.Done THEN
				TopState:=2;
		ELSE
			TopState:=88;
			LeftTop_MC_Stop.Execute:=FALSE;
			RightTopLin_MC_Stop.Execute:=FALSE;
			A_StopMC();
		END_IF

	88:
		TopStop:=FALSE;
		TopState:=0;
		TopBusy:=FALSE;
		TopDone:=TRUE;
		Error:=FALSE;
		ErrorID:=0;
		fb_ton1.IN:=FALSE;

	-100:
		FB_PlcEmergencyStop();
		TopStop:=FALSE;
		TopState:=-100;
		TopBusy:=FALSE;
		TopDone:=FALSE;
		Error:=TRUE;
		LeftTop_MC_Stop.Execute:=FALSE;
		RightTopLin_MC_Stop.Execute:=FALSE;
		A_StopMC();
		fb_ton1.IN:=FALSE;

END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="FB_Stop">
      <LineId Id="72" Count="0" />
      <LineId Id="75" Count="3" />
      <LineId Id="81" Count="14" />
    </LineIds>
    <LineIds Name="FB_Stop.A_BCGapStop">
      <LineId Id="0" Count="7" />
      <LineId Id="63" Count="2" />
      <LineId Id="8" Count="4" />
      <LineId Id="66" Count="3" />
      <LineId Id="13" Count="9" />
      <LineId Id="72" Count="2" />
      <LineId Id="70" Count="0" />
      <LineId Id="23" Count="3" />
      <LineId Id="75" Count="0" />
      <LineId Id="77" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="27" Count="6" />
      <LineId Id="80" Count="2" />
      <LineId Id="78" Count="0" />
      <LineId Id="34" Count="21" />
      <LineId Id="83" Count="3" />
      <LineId Id="56" Count="5" />
    </LineIds>
    <LineIds Name="FB_Stop.A_BottomStop">
      <LineId Id="0" Count="10" />
      <LineId Id="51" Count="0" />
      <LineId Id="11" Count="5" />
      <LineId Id="52" Count="0" />
      <LineId Id="17" Count="7" />
      <LineId Id="53" Count="0" />
      <LineId Id="25" Count="19" />
      <LineId Id="54" Count="0" />
      <LineId Id="45" Count="4" />
    </LineIds>
    <LineIds Name="FB_Stop.A_InStop">
      <LineId Id="0" Count="16" />
      <LineId Id="51" Count="0" />
      <LineId Id="17" Count="7" />
      <LineId Id="52" Count="0" />
      <LineId Id="25" Count="19" />
      <LineId Id="53" Count="0" />
      <LineId Id="45" Count="4" />
    </LineIds>
    <LineIds Name="FB_Stop.A_LeftBottomStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_LeftInStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_LeftOutStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_LeftTopStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_OutStop">
      <LineId Id="0" Count="10" />
      <LineId Id="51" Count="0" />
      <LineId Id="11" Count="5" />
      <LineId Id="52" Count="0" />
      <LineId Id="17" Count="7" />
      <LineId Id="53" Count="0" />
      <LineId Id="25" Count="19" />
      <LineId Id="54" Count="0" />
      <LineId Id="45" Count="4" />
    </LineIds>
    <LineIds Name="FB_Stop.A_RightBottomStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_RightInStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_RightOutStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_RightTopStop">
      <LineId Id="0" Count="49" />
    </LineIds>
    <LineIds Name="FB_Stop.A_TopStop">
      <LineId Id="0" Count="16" />
      <LineId Id="51" Count="0" />
      <LineId Id="17" Count="7" />
      <LineId Id="52" Count="0" />
      <LineId Id="25" Count="19" />
      <LineId Id="53" Count="0" />
      <LineId Id="45" Count="4" />
    </LineIds>
  </POU>
</TcPlcObject>